// Code generated by MockGen. DO NOT EDIT.
// Source: internal/pkg/app/cli/app.go
//
// Generated by this command:
//
//	mockgen -source=internal/pkg/app/cli/app.go -destination=internal/pkg/app/cli/mocks/weather_info_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "github.com/kornev-aa/lab5-provider/internal/domain/models"
	gomock "go.uber.org/mock/gomock"
)

// MockLogger is a mock of Logger interface.
type MockLogger struct {
	ctrl     *gomock.Controller
	recorder *MockLoggerMockRecorder
	isgomock struct{}
}

// MockLoggerMockRecorder is the mock recorder for MockLogger.
type MockLoggerMockRecorder struct {
	mock *MockLogger
}

// NewMockLogger creates a new mock instance.
func NewMockLogger(ctrl *gomock.Controller) *MockLogger {
	mock := &MockLogger{ctrl: ctrl}
	mock.recorder = &MockLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogger) EXPECT() *MockLoggerMockRecorder {
	return m.recorder
}

// Debug mocks base method.
func (m *MockLogger) Debug(msg string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Debug", msg)
}

// Debug indicates an expected call of Debug.
func (mr *MockLoggerMockRecorder) Debug(msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Debug", reflect.TypeOf((*MockLogger)(nil).Debug), msg)
}

// Error mocks base method.
func (m *MockLogger) Error(msg string, err error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Error", msg, err)
}

// Error indicates an expected call of Error.
func (mr *MockLoggerMockRecorder) Error(msg, err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockLogger)(nil).Error), msg, err)
}

// Info mocks base method.
func (m *MockLogger) Info(msg string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Info", msg)
}

// Info indicates an expected call of Info.
func (mr *MockLoggerMockRecorder) Info(msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Info", reflect.TypeOf((*MockLogger)(nil).Info), msg)
}

// MockWeatherInfo is a mock of WeatherInfo interface.
type MockWeatherInfo struct {
	ctrl     *gomock.Controller
	recorder *MockWeatherInfoMockRecorder
	isgomock struct{}
}

// MockWeatherInfoMockRecorder is the mock recorder for MockWeatherInfo.
type MockWeatherInfoMockRecorder struct {
	mock *MockWeatherInfo
}

// NewMockWeatherInfo creates a new mock instance.
func NewMockWeatherInfo(ctrl *gomock.Controller) *MockWeatherInfo {
	mock := &MockWeatherInfo{ctrl: ctrl}
	mock.recorder = &MockWeatherInfoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWeatherInfo) EXPECT() *MockWeatherInfoMockRecorder {
	return m.recorder
}

// GetTemperature mocks base method.
func (m *MockWeatherInfo) GetTemperature(lat, lon float64) models.TempInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTemperature", lat, lon)
	ret0, _ := ret[0].(models.TempInfo)
	return ret0
}

// GetTemperature indicates an expected call of GetTemperature.
func (mr *MockWeatherInfoMockRecorder) GetTemperature(lat, lon any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTemperature", reflect.TypeOf((*MockWeatherInfo)(nil).GetTemperature), lat, lon)
}
